// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT e.category, sum(e.amount)::bigint AS amount
FROM expenses e
WHERE e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
  AND e.expense_date >= $1 AND e.expense_date < $2
  AND (e.paid_by_id = $3
       OR EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $3))
GROUP BY e.category
`

type GetCategoryBreakdownParams struct {
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type GetCategoryBreakdownRow struct {
	Category string `json:"category"`
	Amount   int64  `json:"amount"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.StartDate, arg.EndDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryBreakdownRow
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupSpending = `-- name: GetGroupSpending :many
SELECT g.id AS group_id, g.name AS group_name, sum(e.amount)::bigint AS total_spending
FROM group_members gm
JOIN groups g ON g.id = gm.group_id
JOIN expenses e ON e.group_id = g.id
WHERE gm.user_id = $1 AND gm.status = 'ACTIVE'
  AND e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
  AND e.expense_date >= $2 AND e.expense_date < $3
  AND (e.paid_by_id = $1
       OR EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $1))
GROUP BY g.id, g.name
`

type GetGroupSpendingParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type GetGroupSpendingRow struct {
	GroupID       pgtype.UUID `json:"group_id"`
	GroupName     string      `json:"group_name"`
	TotalSpending int64       `json:"total_spending"`
}

// Only groups with actual matching spending appear (an INNER JOIN to
// expenses naturally excludes an active membership with zero spend in
// the period, same as the original's post-hoc "> 0" filter).
func (q *Queries) GetGroupSpending(ctx context.Context, arg GetGroupSpendingParams) ([]GetGroupSpendingRow, error) {
	rows, err := q.db.Query(ctx, getGroupSpending, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupSpendingRow
	for rows.Next() {
		var i GetGroupSpendingRow
		if err := rows.Scan(&i.GroupID, &i.GroupName, &i.TotalSpending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrendRaw = `-- name: GetMonthlyTrendRaw :many
SELECT EXTRACT(MONTH FROM e.expense_date)::int AS month, sum(e.amount)::bigint AS total_spending
FROM expenses e
WHERE e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
  AND e.expense_date >= $1 AND e.expense_date < $2
  AND (e.paid_by_id = $3
       OR EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $3))
GROUP BY EXTRACT(MONTH FROM e.expense_date)
`

type GetMonthlyTrendRawParams struct {
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type GetMonthlyTrendRawRow struct {
	Month         int32 `json:"month"`
	TotalSpending int64 `json:"total_spending"`
}

// Only months with matching spending are returned; the caller fills the
// other months of the year with zero.
func (q *Queries) GetMonthlyTrendRaw(ctx context.Context, arg GetMonthlyTrendRawParams) ([]GetMonthlyTrendRawRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrendRaw, arg.StartDate, arg.EndDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTrendRawRow
	for rows.Next() {
		var i GetMonthlyTrendRawRow
		if err := rows.Scan(&i.Month, &i.TotalSpending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettlementsPaid = `-- name: GetSettlementsPaid :one
SELECT COALESCE(sum(amount), 0)::bigint FROM expenses
WHERE paid_by_id = $1 AND split_type = 'SETTLEMENT' AND deleted_at IS NULL
  AND expense_date >= $2 AND expense_date < $3
`

type GetSettlementsPaidParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

// direction "paid": settlements the user initiated (paid_by_id = user).
func (q *Queries) GetSettlementsPaid(ctx context.Context, arg GetSettlementsPaidParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSettlementsPaid, arg.UserID, arg.StartDate, arg.EndDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSettlementsReceived = `-- name: GetSettlementsReceived :one
SELECT COALESCE(sum(ep.amount), 0)::bigint
FROM expense_participants ep
JOIN expenses e ON e.id = ep.expense_id
WHERE ep.user_id = $1 AND ep.amount > 0 AND e.paid_by_id != $1
  AND e.split_type = 'SETTLEMENT' AND e.deleted_at IS NULL
  AND e.expense_date >= $2 AND e.expense_date < $3
`

type GetSettlementsReceivedParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

// direction "received": settlements where the user is the recipient
// participant (see settlements.Service -- recipient's amount carries the
// settled amount, payer's is always 0).
func (q *Queries) GetSettlementsReceived(ctx context.Context, arg GetSettlementsReceivedParams) (int64, error) {
	row := q.db.QueryRow(ctx, getSettlementsReceived, arg.UserID, arg.StartDate, arg.EndDate)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserTotals = `-- name: GetUserTotals :one

WITH involved AS (
    SELECT DISTINCT e.id, e.amount
    FROM expenses e
    LEFT JOIN expense_participants ep ON ep.expense_id = e.id AND ep.user_id = $1
    WHERE e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
      AND e.expense_date >= $2 AND e.expense_date < $3
      AND (e.paid_by_id = $1 OR ep.user_id = $1)
)
SELECT
    COALESCE((SELECT sum(amount) FROM involved), 0)::bigint AS total_spending,
    COALESCE((
        SELECT sum(e.amount) FROM expenses e
        WHERE e.paid_by_id = $1 AND e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
          AND e.expense_date >= $2 AND e.expense_date < $3
    ), 0)::bigint AS your_contribution,
    COALESCE((
        SELECT sum(ep.amount) FROM expense_participants ep JOIN expenses e ON e.id = ep.expense_id
        WHERE ep.user_id = $1 AND e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
          AND e.expense_date >= $2 AND e.expense_date < $3
    ), 0)::bigint AS your_share,
    COALESCE((
        SELECT sum(ep.amount) FROM expense_participants ep JOIN expenses e ON e.id = ep.expense_id
        WHERE ep.user_id = $1 AND e.paid_by_id != $1
          AND e.split_type != 'SETTLEMENT' AND e.deleted_at IS NULL
          AND e.expense_date >= $2 AND e.expense_date < $3
    ), 0)::bigint AS amount_owed
`

type GetUserTotalsParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type GetUserTotalsRow struct {
	TotalSpending    int64 `json:"total_spending"`
	YourContribution int64 `json:"your_contribution"`
	YourShare        int64 `json:"your_share"`
	AmountOwed       int64 `json:"amount_owed"`
}

// Read-only aggregation over expenses/expense_participants -- ABRO_PRD.md
// §26. All queries exclude soft-deleted expenses and SETTLEMENT-type rows
// (settlements are reported separately, to avoid double-counting a debt
// transfer as new "spending").
// Total Spending / Your Contribution / Your Share / amount owed for the
// period.
func (q *Queries) GetUserTotals(ctx context.Context, arg GetUserTotalsParams) (GetUserTotalsRow, error) {
	row := q.db.QueryRow(ctx, getUserTotals, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetUserTotalsRow
	err := row.Scan(
		&i.TotalSpending,
		&i.YourContribution,
		&i.YourShare,
		&i.AmountOwed,
	)
	return i, err
}
