// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOtpCode = `-- name: ConsumeOtpCode :exec
UPDATE otp_codes SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeOtpCode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, consumeOtpCode, id)
	return err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_account_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_account_id, created_at
`

type CreateOAuthAccountParams struct {
	UserID            pgtype.UUID   `json:"user_id"`
	Provider          OauthProvider `json:"provider"`
	ProviderAccountID string        `json:"provider_account_id"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderAccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const createOtpCode = `-- name: CreateOtpCode :one
INSERT INTO otp_codes (email, code_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, code_hash, attempts, consumed_at, expires_at, created_at
`

type CreateOtpCodeParams struct {
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOtpCode, arg.Email, arg.CodeHash, arg.ExpiresAt)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip_address, created_at, last_used_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getLatestUnconsumedOtpCode = `-- name: GetLatestUnconsumedOtpCode :one
SELECT id, email, code_hash, attempts, consumed_at, expires_at, created_at FROM otp_codes
WHERE email = $1 AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUnconsumedOtpCode(ctx context.Context, email string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestUnconsumedOtpCode, email)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccountByProvider = `-- name: GetOAuthAccountByProvider :one
SELECT id, user_id, provider, provider_account_id, created_at FROM oauth_accounts WHERE provider = $1 AND provider_account_id = $2
`

type GetOAuthAccountByProviderParams struct {
	Provider          OauthProvider `json:"provider"`
	ProviderAccountID string        `json:"provider_account_id"`
}

func (q *Queries) GetOAuthAccountByProvider(ctx context.Context, arg GetOAuthAccountByProviderParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByProvider, arg.Provider, arg.ProviderAccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentOtpCode = `-- name: GetRecentOtpCode :one
SELECT id, email, code_hash, attempts, consumed_at, expires_at, created_at FROM otp_codes
WHERE email = $1 AND created_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type GetRecentOtpCodeParams struct {
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Cooldown check: most recent OTP sent for this email since `since`.
func (q *Queries) GetRecentOtpCode(ctx context.Context, arg GetRecentOtpCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getRecentOtpCode, arg.Email, arg.CreatedAt)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ConsumedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, user_agent, ip_address, created_at, last_used_at, expires_at, revoked_at FROM sessions WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const incrementOtpAttempts = `-- name: IncrementOtpAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOtpAttempts, id)
	return err
}

const revokeSessionsByTokenHash = `-- name: RevokeSessionsByTokenHash :exec
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionsByTokenHash, tokenHash)
	return err
}

const touchSessionLastUsed = `-- name: TouchSessionLastUsed :exec
UPDATE sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchSessionLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastUsed, id)
	return err
}
