// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGroupOwedSums = `-- name: GetGroupOwedSums :many
SELECT ep.user_id, sum(ep.amount)::bigint AS total FROM expense_participants ep
JOIN expenses e ON e.id = ep.expense_id
WHERE e.group_id = $1 AND e.deleted_at IS NULL
GROUP BY ep.user_id
`

type GetGroupOwedSumsRow struct {
	UserID pgtype.UUID `json:"user_id"`
	Total  int64       `json:"total"`
}

func (q *Queries) GetGroupOwedSums(ctx context.Context, groupID pgtype.UUID) ([]GetGroupOwedSumsRow, error) {
	rows, err := q.db.Query(ctx, getGroupOwedSums, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupOwedSumsRow
	for rows.Next() {
		var i GetGroupOwedSumsRow
		if err := rows.Scan(&i.UserID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupPaidSums = `-- name: GetGroupPaidSums :many
SELECT paid_by_id, sum(amount)::bigint AS total FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL
GROUP BY paid_by_id
`

type GetGroupPaidSumsRow struct {
	PaidByID pgtype.UUID `json:"paid_by_id"`
	Total    int64       `json:"total"`
}

func (q *Queries) GetGroupPaidSums(ctx context.Context, groupID pgtype.UUID) ([]GetGroupPaidSumsRow, error) {
	rows, err := q.db.Query(ctx, getGroupPaidSums, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPaidSumsRow
	for rows.Next() {
		var i GetGroupPaidSumsRow
		if err := rows.Scan(&i.PaidByID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairwiseParticipantsInGroup = `-- name: GetPairwiseParticipantsInGroup :many
SELECT ep.user_id, ep.amount FROM expense_participants ep
JOIN expenses e ON e.id = ep.expense_id
WHERE e.deleted_at IS NULL AND e.group_id = $1 AND (
    (ep.user_id = $2 AND e.paid_by_id = $3)
    OR (ep.user_id = $3 AND e.paid_by_id = $2)
)
`

type GetPairwiseParticipantsInGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserB   pgtype.UUID `json:"user_b"`
	UserA   pgtype.UUID `json:"user_a"`
}

type GetPairwiseParticipantsInGroupRow struct {
	UserID pgtype.UUID `json:"user_id"`
	Amount int64       `json:"amount"`
}

func (q *Queries) GetPairwiseParticipantsInGroup(ctx context.Context, arg GetPairwiseParticipantsInGroupParams) ([]GetPairwiseParticipantsInGroupRow, error) {
	rows, err := q.db.Query(ctx, getPairwiseParticipantsInGroup, arg.GroupID, arg.UserB, arg.UserA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPairwiseParticipantsInGroupRow
	for rows.Next() {
		var i GetPairwiseParticipantsInGroupRow
		if err := rows.Scan(&i.UserID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPairwiseParticipantsPersonal = `-- name: GetPairwiseParticipantsPersonal :many
SELECT ep.user_id, ep.amount FROM expense_participants ep
JOIN expenses e ON e.id = ep.expense_id
WHERE e.deleted_at IS NULL AND e.group_id IS NULL AND (
    (ep.user_id = $1 AND e.paid_by_id = $2)
    OR (ep.user_id = $2 AND e.paid_by_id = $1)
)
`

type GetPairwiseParticipantsPersonalParams struct {
	UserB pgtype.UUID `json:"user_b"`
	UserA pgtype.UUID `json:"user_a"`
}

type GetPairwiseParticipantsPersonalRow struct {
	UserID pgtype.UUID `json:"user_id"`
	Amount int64       `json:"amount"`
}

// Personal-scope (group_id IS NULL) half of getPairwiseBalance's OR query.
func (q *Queries) GetPairwiseParticipantsPersonal(ctx context.Context, arg GetPairwiseParticipantsPersonalParams) ([]GetPairwiseParticipantsPersonalRow, error) {
	rows, err := q.db.Query(ctx, getPairwiseParticipantsPersonal, arg.UserB, arg.UserA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPairwiseParticipantsPersonalRow
	for rows.Next() {
		var i GetPairwiseParticipantsPersonalRow
		if err := rows.Scan(&i.UserID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupShareRows = `-- name: ListGroupShareRows :many
SELECT e.id AS expense_id, e.paid_by_id, e.amount AS expense_amount, e.created_at,
       ep.user_id, ep.amount AS share
FROM expenses e
JOIN expense_participants ep ON ep.expense_id = e.id
WHERE e.group_id = $1 AND e.deleted_at IS NULL
ORDER BY e.created_at, e.id
`

type ListGroupShareRowsRow struct {
	ExpenseID     pgtype.UUID        `json:"expense_id"`
	PaidByID      pgtype.UUID        `json:"paid_by_id"`
	ExpenseAmount int64              `json:"expense_amount"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	Share         int64              `json:"share"`
}

// Every share of every live expense in a group, in the order the
// expenses were added -- each member's movements in the group (ADR-023).
func (q *Queries) ListGroupShareRows(ctx context.Context, groupID pgtype.UUID) ([]ListGroupShareRowsRow, error) {
	rows, err := q.db.Query(ctx, listGroupShareRows, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupShareRowsRow
	for rows.Next() {
		var i ListGroupShareRowsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.PaidByID,
			&i.ExpenseAmount,
			&i.CreatedAt,
			&i.UserID,
			&i.Share,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPairwiseMovementsPersonal = `-- name: ListPairwiseMovementsPersonal :many
SELECT ep.user_id, ep.amount, e.created_at FROM expense_participants ep
JOIN expenses e ON e.id = ep.expense_id
WHERE e.deleted_at IS NULL AND e.group_id IS NULL AND (
    (ep.user_id = $1 AND e.paid_by_id = $2)
    OR (ep.user_id = $2 AND e.paid_by_id = $1)
)
ORDER BY e.created_at, e.id
`

type ListPairwiseMovementsPersonalParams struct {
	UserB pgtype.UUID `json:"user_b"`
	UserA pgtype.UUID `json:"user_a"`
}

type ListPairwiseMovementsPersonalRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Amount    int64              `json:"amount"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// GetPairwiseParticipantsPersonal in the order the expenses were added,
// for how long a debt has been open (ADR-023). Added, not dated: an
// expense back-dated today is new debt today.
func (q *Queries) ListPairwiseMovementsPersonal(ctx context.Context, arg ListPairwiseMovementsPersonalParams) ([]ListPairwiseMovementsPersonalRow, error) {
	rows, err := q.db.Query(ctx, listPairwiseMovementsPersonal, arg.UserB, arg.UserA)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPairwiseMovementsPersonalRow
	for rows.Next() {
		var i ListPairwiseMovementsPersonalRow
		if err := rows.Scan(&i.UserID, &i.Amount, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
