// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ekubs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEkub = `-- name: CreateEkub :one
INSERT INTO ekubs (name, currency, slot_amount, cadence, created_by_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, currency, slot_amount, cadence, status, start_date, created_by_id, created_at
`

type CreateEkubParams struct {
	Name        string      `json:"name"`
	Currency    string      `json:"currency"`
	SlotAmount  int64       `json:"slot_amount"`
	Cadence     EkubCadence `json:"cadence"`
	CreatedByID pgtype.UUID `json:"created_by_id"`
}

func (q *Queries) CreateEkub(ctx context.Context, arg CreateEkubParams) (Ekub, error) {
	row := q.db.QueryRow(ctx, createEkub,
		arg.Name,
		arg.Currency,
		arg.SlotAmount,
		arg.Cadence,
		arg.CreatedByID,
	)
	var i Ekub
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.SlotAmount,
		&i.Cadence,
		&i.Status,
		&i.StartDate,
		&i.CreatedByID,
		&i.CreatedAt,
	)
	return i, err
}

const createEkubMember = `-- name: CreateEkubMember :one
INSERT INTO ekub_members (ekub_id, user_id, role, status, amount, slot_position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ekub_id, user_id, role, status, amount, slot_position, joined_round, created_at
`

type CreateEkubMemberParams struct {
	EkubID       pgtype.UUID       `json:"ekub_id"`
	UserID       pgtype.UUID       `json:"user_id"`
	Role         GroupMemberRole   `json:"role"`
	Status       GroupMemberStatus `json:"status"`
	Amount       int64             `json:"amount"`
	SlotPosition int32             `json:"slot_position"`
}

func (q *Queries) CreateEkubMember(ctx context.Context, arg CreateEkubMemberParams) (EkubMember, error) {
	row := q.db.QueryRow(ctx, createEkubMember,
		arg.EkubID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.Amount,
		arg.SlotPosition,
	)
	var i EkubMember
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Amount,
		&i.SlotPosition,
		&i.JoinedRound,
		&i.CreatedAt,
	)
	return i, err
}

const createEkubPayment = `-- name: CreateEkubPayment :one
INSERT INTO ekub_payments (ekub_id, payer_member_id, recipient_member_id, amount, status, created_by_id, resolved_at)
VALUES ($1, $2, $3, $4, $5, $6, CASE WHEN $5::ekub_payment_status = 'CONFIRMED' THEN now() END)
RETURNING id, ekub_id, payer_member_id, recipient_member_id, amount, status, created_by_id, created_at, resolved_at
`

type CreateEkubPaymentParams struct {
	EkubID            pgtype.UUID       `json:"ekub_id"`
	PayerMemberID     pgtype.UUID       `json:"payer_member_id"`
	RecipientMemberID pgtype.UUID       `json:"recipient_member_id"`
	Amount            int64             `json:"amount"`
	Status            EkubPaymentStatus `json:"status"`
	CreatedByID       pgtype.UUID       `json:"created_by_id"`
}

func (q *Queries) CreateEkubPayment(ctx context.Context, arg CreateEkubPaymentParams) (EkubPayment, error) {
	row := q.db.QueryRow(ctx, createEkubPayment,
		arg.EkubID,
		arg.PayerMemberID,
		arg.RecipientMemberID,
		arg.Amount,
		arg.Status,
		arg.CreatedByID,
	)
	var i EkubPayment
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.PayerMemberID,
		&i.RecipientMemberID,
		&i.Amount,
		&i.Status,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deleteEkub = `-- name: DeleteEkub :exec
DELETE FROM ekubs WHERE id = $1
`

func (q *Queries) DeleteEkub(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEkub, id)
	return err
}

const deleteEkubMember = `-- name: DeleteEkubMember :exec
DELETE FROM ekub_members WHERE id = $1
`

func (q *Queries) DeleteEkubMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEkubMember, id)
	return err
}

const getEkub = `-- name: GetEkub :one
SELECT id, name, currency, slot_amount, cadence, status, start_date, created_by_id, created_at FROM ekubs WHERE id = $1
`

func (q *Queries) GetEkub(ctx context.Context, id pgtype.UUID) (Ekub, error) {
	row := q.db.QueryRow(ctx, getEkub, id)
	var i Ekub
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.SlotAmount,
		&i.Cadence,
		&i.Status,
		&i.StartDate,
		&i.CreatedByID,
		&i.CreatedAt,
	)
	return i, err
}

const getEkubMember = `-- name: GetEkubMember :one
SELECT id, ekub_id, user_id, role, status, amount, slot_position, joined_round, created_at FROM ekub_members WHERE id = $1 AND ekub_id = $2
`

type GetEkubMemberParams struct {
	ID     pgtype.UUID `json:"id"`
	EkubID pgtype.UUID `json:"ekub_id"`
}

func (q *Queries) GetEkubMember(ctx context.Context, arg GetEkubMemberParams) (EkubMember, error) {
	row := q.db.QueryRow(ctx, getEkubMember, arg.ID, arg.EkubID)
	var i EkubMember
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Amount,
		&i.SlotPosition,
		&i.JoinedRound,
		&i.CreatedAt,
	)
	return i, err
}

const getEkubMemberByUser = `-- name: GetEkubMemberByUser :one
SELECT id, ekub_id, user_id, role, status, amount, slot_position, joined_round, created_at FROM ekub_members WHERE ekub_id = $1 AND user_id = $2
`

type GetEkubMemberByUserParams struct {
	EkubID pgtype.UUID `json:"ekub_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetEkubMemberByUser(ctx context.Context, arg GetEkubMemberByUserParams) (EkubMember, error) {
	row := q.db.QueryRow(ctx, getEkubMemberByUser, arg.EkubID, arg.UserID)
	var i EkubMember
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Amount,
		&i.SlotPosition,
		&i.JoinedRound,
		&i.CreatedAt,
	)
	return i, err
}

const getEkubPayment = `-- name: GetEkubPayment :one
SELECT id, ekub_id, payer_member_id, recipient_member_id, amount, status, created_by_id, created_at, resolved_at FROM ekub_payments WHERE id = $1 AND ekub_id = $2
`

type GetEkubPaymentParams struct {
	ID     pgtype.UUID `json:"id"`
	EkubID pgtype.UUID `json:"ekub_id"`
}

func (q *Queries) GetEkubPayment(ctx context.Context, arg GetEkubPaymentParams) (EkubPayment, error) {
	row := q.db.QueryRow(ctx, getEkubPayment, arg.ID, arg.EkubID)
	var i EkubPayment
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.PayerMemberID,
		&i.RecipientMemberID,
		&i.Amount,
		&i.Status,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const joinStartedEkub = `-- name: JoinStartedEkub :one
WITH shifted AS (
    UPDATE ekub_members s
    SET slot_position = s.slot_position + 1
    WHERE s.ekub_id = $4 AND s.status <> 'INVITED' AND s.slot_position >= $1
)
UPDATE ekub_members j
SET status = 'ACTIVE', slot_position = $1, joined_round = $2
WHERE j.id = $3
RETURNING j.id, j.ekub_id, j.user_id, j.role, j.status, j.amount, j.slot_position, j.joined_round, j.created_at
`

type JoinStartedEkubParams struct {
	SlotPosition int32       `json:"slot_position"`
	JoinedRound  int32       `json:"joined_round"`
	MemberID     pgtype.UUID `json:"member_id"`
	EkubID       pgtype.UUID `json:"ekub_id"`
}

// Someone invited after the start accepts: their slot goes in at
// `slot_position` and every taking-part slot from there moves one round
// later, in the same statement.
func (q *Queries) JoinStartedEkub(ctx context.Context, arg JoinStartedEkubParams) (EkubMember, error) {
	row := q.db.QueryRow(ctx, joinStartedEkub,
		arg.SlotPosition,
		arg.JoinedRound,
		arg.MemberID,
		arg.EkubID,
	)
	var i EkubMember
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Amount,
		&i.SlotPosition,
		&i.JoinedRound,
		&i.CreatedAt,
	)
	return i, err
}

const listEkubMembers = `-- name: ListEkubMembers :many
SELECT m.id, m.ekub_id, m.user_id, m.role, m.status, m.amount, m.slot_position, m.joined_round, m.created_at, p.display_name, p.avatar_url, p.username
FROM ekub_members m
JOIN profiles p ON p.id = m.user_id
WHERE m.ekub_id = $1
ORDER BY m.slot_position, m.created_at
`

type ListEkubMembersRow struct {
	ID           pgtype.UUID        `json:"id"`
	EkubID       pgtype.UUID        `json:"ekub_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         GroupMemberRole    `json:"role"`
	Status       GroupMemberStatus  `json:"status"`
	Amount       int64              `json:"amount"`
	SlotPosition int32              `json:"slot_position"`
	JoinedRound  int32              `json:"joined_round"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Username     pgtype.Text        `json:"username"`
}

func (q *Queries) ListEkubMembers(ctx context.Context, ekubID pgtype.UUID) ([]ListEkubMembersRow, error) {
	rows, err := q.db.Query(ctx, listEkubMembers, ekubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEkubMembersRow
	for rows.Next() {
		var i ListEkubMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.EkubID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.Amount,
			&i.SlotPosition,
			&i.JoinedRound,
			&i.CreatedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEkubPayments = `-- name: ListEkubPayments :many
SELECT id, ekub_id, payer_member_id, recipient_member_id, amount, status, created_by_id, created_at, resolved_at FROM ekub_payments
WHERE ekub_id = $1 AND status <> 'REJECTED'
ORDER BY created_at
`

func (q *Queries) ListEkubPayments(ctx context.Context, ekubID pgtype.UUID) ([]EkubPayment, error) {
	rows, err := q.db.Query(ctx, listEkubPayments, ekubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EkubPayment
	for rows.Next() {
		var i EkubPayment
		if err := rows.Scan(
			&i.ID,
			&i.EkubID,
			&i.PayerMemberID,
			&i.RecipientMemberID,
			&i.Amount,
			&i.Status,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEkubs = `-- name: ListMyEkubs :many
SELECT e.id, e.name, e.currency, e.slot_amount, e.cadence, e.status, e.start_date, e.created_by_id, e.created_at, m.status AS my_status, m.role AS my_role,
       (SELECT count(*) FROM ekub_members x
        WHERE x.ekub_id = e.id AND x.status <> 'INVITED')::int AS member_count
FROM ekubs e
JOIN ekub_members m ON m.ekub_id = e.id
WHERE m.user_id = $1 AND m.status <> 'LEFT'
ORDER BY e.created_at DESC
`

type ListMyEkubsRow struct {
	Ekub        Ekub              `json:"ekub"`
	MyStatus    GroupMemberStatus `json:"my_status"`
	MyRole      GroupMemberRole   `json:"my_role"`
	MemberCount int32             `json:"member_count"`
}

// Every ekub the user is in or invited to (not ones they left), with
// their own membership and the number of people taking part.
func (q *Queries) ListMyEkubs(ctx context.Context, userID pgtype.UUID) ([]ListMyEkubsRow, error) {
	rows, err := q.db.Query(ctx, listMyEkubs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyEkubsRow
	for rows.Next() {
		var i ListMyEkubsRow
		if err := rows.Scan(
			&i.Ekub.ID,
			&i.Ekub.Name,
			&i.Ekub.Currency,
			&i.Ekub.SlotAmount,
			&i.Ekub.Cadence,
			&i.Ekub.Status,
			&i.Ekub.StartDate,
			&i.Ekub.CreatedByID,
			&i.Ekub.CreatedAt,
			&i.MyStatus,
			&i.MyRole,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEkubPayment = `-- name: ResolveEkubPayment :one
UPDATE ekub_payments SET status = $2, resolved_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, ekub_id, payer_member_id, recipient_member_id, amount, status, created_by_id, created_at, resolved_at
`

type ResolveEkubPaymentParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status EkubPaymentStatus `json:"status"`
}

// Only a payment still waiting can be confirmed or turned down; no row
// back means someone else got there first.
func (q *Queries) ResolveEkubPayment(ctx context.Context, arg ResolveEkubPaymentParams) (EkubPayment, error) {
	row := q.db.QueryRow(ctx, resolveEkubPayment, arg.ID, arg.Status)
	var i EkubPayment
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.PayerMemberID,
		&i.RecipientMemberID,
		&i.Amount,
		&i.Status,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const setEkubMemberStatus = `-- name: SetEkubMemberStatus :one
UPDATE ekub_members SET status = $2 WHERE id = $1
RETURNING id, ekub_id, user_id, role, status, amount, slot_position, joined_round, created_at
`

type SetEkubMemberStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status GroupMemberStatus `json:"status"`
}

func (q *Queries) SetEkubMemberStatus(ctx context.Context, arg SetEkubMemberStatusParams) (EkubMember, error) {
	row := q.db.QueryRow(ctx, setEkubMemberStatus, arg.ID, arg.Status)
	var i EkubMember
	err := row.Scan(
		&i.ID,
		&i.EkubID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Amount,
		&i.SlotPosition,
		&i.JoinedRound,
		&i.CreatedAt,
	)
	return i, err
}

const setEkubSlots = `-- name: SetEkubSlots :exec
UPDATE ekub_members m
SET slot_position = v.slot_position, amount = v.amount
FROM (SELECT unnest($2::uuid[]) AS id,
             unnest($3::int[]) AS slot_position,
             unnest($4::bigint[]) AS amount) v
WHERE m.id = v.id AND m.ekub_id = $1
`

type SetEkubSlotsParams struct {
	EkubID        pgtype.UUID   `json:"ekub_id"`
	MemberIds     []pgtype.UUID `json:"member_ids"`
	SlotPositions []int32       `json:"slot_positions"`
	Amounts       []int64       `json:"amounts"`
}

// The admin's new arrangement, in one statement so it lands whole.
func (q *Queries) SetEkubSlots(ctx context.Context, arg SetEkubSlotsParams) error {
	_, err := q.db.Exec(ctx, setEkubSlots,
		arg.EkubID,
		arg.MemberIds,
		arg.SlotPositions,
		arg.Amounts,
	)
	return err
}

const startEkub = `-- name: StartEkub :one
UPDATE ekubs SET status = 'ACTIVE', start_date = $2
WHERE id = $1 AND status = 'DRAFT'
RETURNING id, name, currency, slot_amount, cadence, status, start_date, created_by_id, created_at
`

type StartEkubParams struct {
	ID        pgtype.UUID `json:"id"`
	StartDate pgtype.Date `json:"start_date"`
}

func (q *Queries) StartEkub(ctx context.Context, arg StartEkubParams) (Ekub, error) {
	row := q.db.QueryRow(ctx, startEkub, arg.ID, arg.StartDate)
	var i Ekub
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.SlotAmount,
		&i.Cadence,
		&i.Status,
		&i.StartDate,
		&i.CreatedByID,
		&i.CreatedAt,
	)
	return i, err
}
