// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes, conversion_id, deleted_at, deleted_by_id, created_at, updated_at, updated_by_id
`

type CreateExpenseParams struct {
	GroupID     pgtype.UUID        `json:"group_id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	PaidByID    pgtype.UUID        `json:"paid_by_id"`
	SplitType   SplitType          `json:"split_type"`
	ExpenseDate pgtype.Timestamptz `json:"expense_date"`
	ReceiptPath pgtype.Text        `json:"receipt_path"`
	Notes       pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.Currency,
		arg.PaidByID,
		arg.SplitType,
		arg.ExpenseDate,
		arg.ReceiptPath,
		arg.Notes,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitType,
		&i.ExpenseDate,
		&i.ReceiptPath,
		&i.Notes,
		&i.ConversionID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}

const createExpenseNote = `-- name: CreateExpenseNote :one
INSERT INTO expense_notes (expense_id, author_id, content)
VALUES ($1, $2, $3)
RETURNING id, expense_id, author_id, content, created_at
`

type CreateExpenseNoteParams struct {
	ExpenseID pgtype.UUID `json:"expense_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	Content   string      `json:"content"`
}

func (q *Queries) CreateExpenseNote(ctx context.Context, arg CreateExpenseNoteParams) (ExpenseNote, error) {
	row := q.db.QueryRow(ctx, createExpenseNote, arg.ExpenseID, arg.AuthorID, arg.Content)
	var i ExpenseNote
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createExpenseParticipant = `-- name: CreateExpenseParticipant :one
INSERT INTO expense_participants (expense_id, user_id, amount)
VALUES ($1, $2, $3)
RETURNING id, expense_id, user_id, amount
`

type CreateExpenseParticipantParams struct {
	ExpenseID pgtype.UUID `json:"expense_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Amount    int64       `json:"amount"`
}

func (q *Queries) CreateExpenseParticipant(ctx context.Context, arg CreateExpenseParticipantParams) (ExpenseParticipant, error) {
	row := q.db.QueryRow(ctx, createExpenseParticipant, arg.ExpenseID, arg.UserID, arg.Amount)
	var i ExpenseParticipant
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
	)
	return i, err
}

const deleteExpenseParticipants = `-- name: DeleteExpenseParticipants :exec
DELETE FROM expense_participants WHERE expense_id = $1
`

func (q *Queries) DeleteExpenseParticipants(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseParticipants, expenseID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes, conversion_id, deleted_at, deleted_by_id, created_at, updated_at, updated_by_id FROM expenses WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id pgtype.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitType,
		&i.ExpenseDate,
		&i.ReceiptPath,
		&i.Notes,
		&i.ConversionID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}

const getExpenseParticipant = `-- name: GetExpenseParticipant :one
SELECT id, expense_id, user_id, amount FROM expense_participants WHERE expense_id = $1 AND user_id = $2
`

type GetExpenseParticipantParams struct {
	ExpenseID pgtype.UUID `json:"expense_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetExpenseParticipant(ctx context.Context, arg GetExpenseParticipantParams) (ExpenseParticipant, error) {
	row := q.db.QueryRow(ctx, getExpenseParticipant, arg.ExpenseID, arg.UserID)
	var i ExpenseParticipant
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.Amount,
	)
	return i, err
}

const listExpenseNotesWithAuthor = `-- name: ListExpenseNotesWithAuthor :many
SELECT n.id, n.expense_id, n.content, n.created_at,
       p.id AS author_id, p.display_name AS author_display_name, p.avatar_url AS author_avatar_url,
       p.email AS author_email, p.preferred_currency AS author_preferred_currency, p.locale AS author_locale
FROM expense_notes n
JOIN profiles p ON p.id = n.author_id
WHERE n.expense_id = $1
ORDER BY n.created_at ASC
`

type ListExpenseNotesWithAuthorRow struct {
	ID                      pgtype.UUID        `json:"id"`
	ExpenseID               pgtype.UUID        `json:"expense_id"`
	Content                 string             `json:"content"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	AuthorID                pgtype.UUID        `json:"author_id"`
	AuthorDisplayName       string             `json:"author_display_name"`
	AuthorAvatarUrl         pgtype.Text        `json:"author_avatar_url"`
	AuthorEmail             pgtype.Text        `json:"author_email"`
	AuthorPreferredCurrency string             `json:"author_preferred_currency"`
	AuthorLocale            string             `json:"author_locale"`
}

func (q *Queries) ListExpenseNotesWithAuthor(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseNotesWithAuthorRow, error) {
	rows, err := q.db.Query(ctx, listExpenseNotesWithAuthor, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseNotesWithAuthorRow
	for rows.Next() {
		var i ListExpenseNotesWithAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.Content,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.AuthorEmail,
			&i.AuthorPreferredCurrency,
			&i.AuthorLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseParticipantsForExpenseIDs = `-- name: ListExpenseParticipantsForExpenseIDs :many
SELECT ep.expense_id, ep.id, ep.user_id, ep.amount,
       p.display_name, p.avatar_url, p.email, p.preferred_currency, p.locale
FROM expense_participants ep
JOIN profiles p ON p.id = ep.user_id
WHERE ep.expense_id = ANY($1::uuid[])
`

type ListExpenseParticipantsForExpenseIDsRow struct {
	ExpenseID         pgtype.UUID `json:"expense_id"`
	ID                pgtype.UUID `json:"id"`
	UserID            pgtype.UUID `json:"user_id"`
	Amount            int64       `json:"amount"`
	DisplayName       string      `json:"display_name"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	Email             pgtype.Text `json:"email"`
	PreferredCurrency string      `json:"preferred_currency"`
	Locale            string      `json:"locale"`
}

func (q *Queries) ListExpenseParticipantsForExpenseIDs(ctx context.Context, expenseIds []pgtype.UUID) ([]ListExpenseParticipantsForExpenseIDsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseParticipantsForExpenseIDs, expenseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseParticipantsForExpenseIDsRow
	for rows.Next() {
		var i ListExpenseParticipantsForExpenseIDsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Email,
			&i.PreferredCurrency,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT id, group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes, conversion_id, deleted_at, deleted_by_id, created_at, updated_at, updated_by_id FROM expenses WHERE group_id = $1 AND deleted_at IS NULL
ORDER BY expense_date DESC, created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListExpensesByGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListExpensesByGroup(ctx context.Context, arg ListExpensesByGroupParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitType,
			&i.ExpenseDate,
			&i.ReceiptPath,
			&i.Notes,
			&i.ConversionID,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesWithFriend = `-- name: ListExpensesWithFriend :many
SELECT e.id, e.group_id, e.name, e.category, e.amount, e.currency, e.paid_by_id, e.split_type, e.expense_date, e.receipt_path, e.notes, e.conversion_id, e.deleted_at, e.deleted_by_id, e.created_at, e.updated_at, e.updated_by_id FROM expenses e
WHERE e.group_id IS NULL AND e.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $1)
  AND EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $2)
ORDER BY e.expense_date DESC, e.created_at DESC, e.id DESC
LIMIT $3 OFFSET $4
`

type ListExpensesWithFriendParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

// Personal (non-group) expenses shared between the actor and a specific
// friend -- ABRO_PRD.md §22 "Friend Balance" history list.
func (q *Queries) ListExpensesWithFriend(ctx context.Context, arg ListExpensesWithFriendParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesWithFriend,
		arg.UserID,
		arg.UserID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitType,
			&i.ExpenseDate,
			&i.ReceiptPath,
			&i.Notes,
			&i.ConversionID,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyExpenses = `-- name: ListMyExpenses :many
SELECT id, group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes, conversion_id, deleted_at, deleted_by_id, created_at, updated_at, updated_by_id FROM expenses e
WHERE e.deleted_at IS NULL AND (
    (e.group_id IS NULL AND EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $1))
    OR (e.group_id IS NOT NULL AND EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'ACTIVE'))
)
ORDER BY e.expense_date DESC, e.created_at DESC, e.id DESC
LIMIT $2 OFFSET $3
`

type ListMyExpensesParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// All three expense list queries order by (expense_date, created_at, id)
// DESC: expense_date alone isn't unique (same-day expenses are common),
// and LIMIT/OFFSET paging over a non-total order can skip or repeat rows
// across pages. created_at puts later-entered same-day expenses first;
// id makes the order total.
// Personal (non-group) expenses the actor participates in, plus every
// expense in a group the actor is an ACTIVE member of.
func (q *Queries) ListMyExpenses(ctx context.Context, arg ListMyExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listMyExpenses, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Category,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitType,
			&i.ExpenseDate,
			&i.ReceiptPath,
			&i.Notes,
			&i.ConversionID,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET deleted_at = now(), deleted_by_id = $2 WHERE id = $1
`

type SoftDeleteExpenseParams struct {
	ID          pgtype.UUID `json:"id"`
	DeletedByID pgtype.UUID `json:"deleted_by_id"`
}

func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, arg.ID, arg.DeletedByID)
	return err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
    group_id = $2, name = $3, category = $4, amount = $5, currency = $6,
    paid_by_id = $7, split_type = $8, expense_date = $9, receipt_path = $10,
    notes = $11, updated_by_id = $12, updated_at = now()
WHERE id = $1
RETURNING id, group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes, conversion_id, deleted_at, deleted_by_id, created_at, updated_at, updated_by_id
`

type UpdateExpenseParams struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	Amount      int64              `json:"amount"`
	Currency    string             `json:"currency"`
	PaidByID    pgtype.UUID        `json:"paid_by_id"`
	SplitType   SplitType          `json:"split_type"`
	ExpenseDate pgtype.Timestamptz `json:"expense_date"`
	ReceiptPath pgtype.Text        `json:"receipt_path"`
	Notes       pgtype.Text        `json:"notes"`
	UpdatedByID pgtype.UUID        `json:"updated_by_id"`
}

// Editing an expense resubmits the whole thing -- a full overwrite, not a
// partial COALESCE update (see updateExpenseSchema == createExpenseSchema).
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Category,
		arg.Amount,
		arg.Currency,
		arg.PaidByID,
		arg.SplitType,
		arg.ExpenseDate,
		arg.ReceiptPath,
		arg.Notes,
		arg.UpdatedByID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitType,
		&i.ExpenseDate,
		&i.ReceiptPath,
		&i.Notes,
		&i.ConversionID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}

const updateExpenseReceiptPath = `-- name: UpdateExpenseReceiptPath :one
UPDATE expenses SET receipt_path = $2 WHERE id = $1 RETURNING id, group_id, name, category, amount, currency, paid_by_id, split_type, expense_date, receipt_path, notes, conversion_id, deleted_at, deleted_by_id, created_at, updated_at, updated_by_id
`

type UpdateExpenseReceiptPathParams struct {
	ID          pgtype.UUID `json:"id"`
	ReceiptPath pgtype.Text `json:"receipt_path"`
}

func (q *Queries) UpdateExpenseReceiptPath(ctx context.Context, arg UpdateExpenseReceiptPathParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpenseReceiptPath, arg.ID, arg.ReceiptPath)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Category,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitType,
		&i.ExpenseDate,
		&i.ReceiptPath,
		&i.Notes,
		&i.ConversionID,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByID,
	)
	return i, err
}
