// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdminsExcept = `-- name: CountActiveAdminsExcept :one
SELECT count(*) FROM group_members
WHERE group_id = $1 AND role = 'ADMIN' AND status = 'ACTIVE' AND user_id != $2
`

type CountActiveAdminsExceptParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountActiveAdminsExcept(ctx context.Context, arg CountActiveAdminsExceptParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminsExcept, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, type, currency, description, simplify_debts, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at
`

type CreateGroupParams struct {
	Name          string      `json:"name"`
	Type          GroupType   `json:"type"`
	Currency      string      `json:"currency"`
	Description   pgtype.Text `json:"description"`
	SimplifyDebts bool        `json:"simplify_debts"`
	CreatedByID   pgtype.UUID `json:"created_by_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Description,
		arg.SimplifyDebts,
		arg.CreatedByID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, user_id, role, status, joined_at
`

type CreateGroupMemberParams struct {
	GroupID pgtype.UUID       `json:"group_id"`
	UserID  pgtype.UUID       `json:"user_id"`
	Role    GroupMemberRole   `json:"role"`
	Status  GroupMemberStatus `json:"status"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, role, status, joined_at FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const listActiveMemberIDsExcept = `-- name: ListActiveMemberIDsExcept :many
SELECT user_id FROM group_members
WHERE group_id = $1 AND status = 'ACTIVE' AND user_id != $2
`

type ListActiveMemberIDsExceptParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListActiveMemberIDsExcept(ctx context.Context, arg ListActiveMemberIDsExceptParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveMemberIDsExcept, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersWithProfiles = `-- name: ListGroupMembersWithProfiles :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.status, gm.joined_at,
       p.display_name, p.avatar_url, p.email, p.preferred_currency, p.locale
FROM group_members gm
JOIN profiles p ON p.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type ListGroupMembersWithProfilesRow struct {
	ID                pgtype.UUID        `json:"id"`
	GroupID           pgtype.UUID        `json:"group_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Role              GroupMemberRole    `json:"role"`
	Status            GroupMemberStatus  `json:"status"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Email             pgtype.Text        `json:"email"`
	PreferredCurrency string             `json:"preferred_currency"`
	Locale            string             `json:"locale"`
}

func (q *Queries) ListGroupMembersWithProfiles(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersWithProfilesRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembersWithProfiles, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersWithProfilesRow
	for rows.Next() {
		var i ListGroupMembersWithProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Email,
			&i.PreferredCurrency,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyActiveGroups = `-- name: ListMyActiveGroups :many
SELECT g.id, g.name, g.type, g.currency, g.description, g.simplify_debts, g.created_by_id, g.created_at, g.updated_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND gm.status = 'ACTIVE'
ORDER BY g.created_at DESC
`

func (q *Queries) ListMyActiveGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listMyActiveGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Description,
			&i.SimplifyDebts,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyInvites = `-- name: ListMyInvites :many
SELECT gm.joined_at AS invited_at, g.id, g.name, g.type, g.currency, g.description, g.simplify_debts, g.created_by_id, g.created_at, g.updated_at
FROM group_members gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1 AND gm.status = 'INVITED'
ORDER BY gm.joined_at DESC
`

type ListMyInvitesRow struct {
	InvitedAt     pgtype.Timestamptz `json:"invited_at"`
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Type          GroupType          `json:"type"`
	Currency      string             `json:"currency"`
	Description   pgtype.Text        `json:"description"`
	SimplifyDebts bool               `json:"simplify_debts"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMyInvites(ctx context.Context, userID pgtype.UUID) ([]ListMyInvitesRow, error) {
	rows, err := q.db.Query(ctx, listMyInvites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyInvitesRow
	for rows.Next() {
		var i ListMyInvitesRow
		if err := rows.Scan(
			&i.InvitedAt,
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Description,
			&i.SimplifyDebts,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reinviteGroupMember = `-- name: ReinviteGroupMember :one
UPDATE group_members
SET status = 'INVITED', role = 'MEMBER', joined_at = now()
WHERE id = $1
RETURNING id, group_id, user_id, role, status, joined_at
`

// joined_at doubles as invitedAt for ListMyInvites -- reset it so a
// re-invite after leaving shows up as a fresh invite, not the stale
// timestamp/ordering from the original membership.
func (q *Queries) ReinviteGroupMember(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, reinviteGroupMember, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = COALESCE($1, name),
    type = COALESCE($2, type),
    currency = COALESCE($3, currency),
    description = COALESCE($4, description),
    simplify_debts = COALESCE($5, simplify_debts),
    updated_at = now()
WHERE id = $6
RETURNING id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at
`

type UpdateGroupParams struct {
	Name          pgtype.Text   `json:"name"`
	Type          NullGroupType `json:"type"`
	Currency      pgtype.Text   `json:"currency"`
	Description   pgtype.Text   `json:"description"`
	SimplifyDebts pgtype.Bool   `json:"simplify_debts"`
	ID            pgtype.UUID   `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Description,
		arg.SimplifyDebts,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :one
UPDATE group_members SET role = $2 WHERE id = $1 RETURNING id, group_id, user_id, role, status, joined_at
`

type UpdateGroupMemberRoleParams struct {
	ID   pgtype.UUID     `json:"id"`
	Role GroupMemberRole `json:"role"`
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberRole, arg.ID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const updateGroupMemberStatus = `-- name: UpdateGroupMemberStatus :one
UPDATE group_members SET status = $2 WHERE id = $1 RETURNING id, group_id, user_id, role, status, joined_at
`

type UpdateGroupMemberStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status GroupMemberStatus `json:"status"`
}

func (q *Queries) UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberStatus, arg.ID, arg.Status)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}
