// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdminsExcept = `-- name: CountActiveAdminsExcept :one
SELECT count(*) FROM group_members
WHERE group_id = $1 AND role = 'ADMIN' AND status = 'ACTIVE' AND user_id != $2
`

type CountActiveAdminsExceptParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountActiveAdminsExcept(ctx context.Context, arg CountActiveAdminsExceptParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminsExcept, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, type, currency, description, simplify_debts, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at, deleted_at, deleted_by_id, photo_path
`

type CreateGroupParams struct {
	Name          string      `json:"name"`
	Type          GroupType   `json:"type"`
	Currency      string      `json:"currency"`
	Description   pgtype.Text `json:"description"`
	SimplifyDebts bool        `json:"simplify_debts"`
	CreatedByID   pgtype.UUID `json:"created_by_id"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Description,
		arg.SimplifyDebts,
		arg.CreatedByID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.PhotoPath,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, user_id, role, status, joined_at
`

type CreateGroupMemberParams struct {
	GroupID pgtype.UUID       `json:"group_id"`
	UserID  pgtype.UUID       `json:"user_id"`
	Role    GroupMemberRole   `json:"role"`
	Status  GroupMemberStatus `json:"status"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at, deleted_at, deleted_by_id, photo_path FROM groups WHERE id = $1 AND deleted_at IS NULL
`

// A deleted group reads as not found (0011_group_soft_delete).
func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.PhotoPath,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.status, gm.joined_at FROM group_members gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.group_id = $1 AND gm.user_id = $2 AND g.deleted_at IS NULL
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

// Every membership check (groups, expenses, balances, settlements,
// recurring) goes through this, so a deleted group's memberships read
// as not found too.
func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const groupHasExpenses = `-- name: GroupHasExpenses :one
SELECT EXISTS (SELECT 1 FROM expenses WHERE group_id = $1 AND deleted_at IS NULL)
`

// GRP-07: the currency can't change once the group has any expense
// (including settlements) -- it would relabel every stored amount.
func (q *Queries) GroupHasExpenses(ctx context.Context, groupID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, groupHasExpenses, groupID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveMemberIDsExcept = `-- name: ListActiveMemberIDsExcept :many
SELECT user_id FROM group_members
WHERE group_id = $1 AND status = 'ACTIVE' AND user_id != $2
`

type ListActiveMemberIDsExceptParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListActiveMemberIDsExcept(ctx context.Context, arg ListActiveMemberIDsExceptParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveMemberIDsExcept, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersWithProfiles = `-- name: ListGroupMembersWithProfiles :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role, gm.status, gm.joined_at,
       p.display_name, p.avatar_url, p.email, p.username, p.preferred_currency, p.locale
FROM group_members gm
JOIN profiles p ON p.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type ListGroupMembersWithProfilesRow struct {
	ID                pgtype.UUID        `json:"id"`
	GroupID           pgtype.UUID        `json:"group_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Role              GroupMemberRole    `json:"role"`
	Status            GroupMemberStatus  `json:"status"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Email             pgtype.Text        `json:"email"`
	Username          pgtype.Text        `json:"username"`
	PreferredCurrency string             `json:"preferred_currency"`
	Locale            string             `json:"locale"`
}

func (q *Queries) ListGroupMembersWithProfiles(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersWithProfilesRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembersWithProfiles, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersWithProfilesRow
	for rows.Next() {
		var i ListGroupMembersWithProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Email,
			&i.Username,
			&i.PreferredCurrency,
			&i.Locale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyActiveGroups = `-- name: ListMyActiveGroups :many
SELECT g.id, g.name, g.type, g.currency, g.description, g.simplify_debts, g.created_by_id, g.created_at, g.updated_at, g.deleted_at, g.deleted_by_id, g.photo_path FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND gm.status = 'ACTIVE' AND g.deleted_at IS NULL
ORDER BY g.created_at DESC
`

func (q *Queries) ListMyActiveGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listMyActiveGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Description,
			&i.SimplifyDebts,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.PhotoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyActiveGroupsWithStats = `-- name: ListMyActiveGroupsWithStats :many
SELECT g.id, g.name, g.type, g.currency, g.description, g.simplify_debts, g.created_by_id, g.created_at, g.updated_at, g.deleted_at, g.deleted_by_id, g.photo_path,
       (SELECT count(*) FROM group_members m
        WHERE m.group_id = g.id AND m.status = 'ACTIVE')::int AS member_count,
       COALESCE((SELECT max(e.created_at) FROM expenses e
                 WHERE e.group_id = g.id AND e.deleted_at IS NULL),
                g.created_at)::timestamptz AS last_activity_at
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND gm.status = 'ACTIVE' AND g.deleted_at IS NULL
ORDER BY g.created_at DESC
`

type ListMyActiveGroupsWithStatsRow struct {
	Group          Group              `json:"group"`
	MemberCount    int32              `json:"member_count"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
}

// Same rows as ListMyActiveGroups, plus the two per-group values the
// DASH-05 Groups list shows on every card: how many ACTIVE members the
// group has (INVITED/LEFT don't count), and when its most recent
// non-deleted expense was recorded (created_at, not the user-chosen,
// possibly backdated expense_date), falling back to the group's own
// created_at for a group with no expenses yet. Correlated subqueries
// rather than a GROUP BY so the embedded groups row stays intact.
func (q *Queries) ListMyActiveGroupsWithStats(ctx context.Context, userID pgtype.UUID) ([]ListMyActiveGroupsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listMyActiveGroupsWithStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyActiveGroupsWithStatsRow
	for rows.Next() {
		var i ListMyActiveGroupsWithStatsRow
		if err := rows.Scan(
			&i.Group.ID,
			&i.Group.Name,
			&i.Group.Type,
			&i.Group.Currency,
			&i.Group.Description,
			&i.Group.SimplifyDebts,
			&i.Group.CreatedByID,
			&i.Group.CreatedAt,
			&i.Group.UpdatedAt,
			&i.Group.DeletedAt,
			&i.Group.DeletedByID,
			&i.Group.PhotoPath,
			&i.MemberCount,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyInvites = `-- name: ListMyInvites :many
SELECT gm.joined_at AS invited_at, g.id, g.name, g.type, g.currency, g.description, g.simplify_debts, g.created_by_id, g.created_at, g.updated_at, g.deleted_at, g.deleted_by_id, g.photo_path
FROM group_members gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1 AND gm.status = 'INVITED' AND g.deleted_at IS NULL
ORDER BY gm.joined_at DESC
`

type ListMyInvitesRow struct {
	InvitedAt     pgtype.Timestamptz `json:"invited_at"`
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Type          GroupType          `json:"type"`
	Currency      string             `json:"currency"`
	Description   pgtype.Text        `json:"description"`
	SimplifyDebts bool               `json:"simplify_debts"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByID   pgtype.UUID        `json:"deleted_by_id"`
	PhotoPath     pgtype.Text        `json:"photo_path"`
}

func (q *Queries) ListMyInvites(ctx context.Context, userID pgtype.UUID) ([]ListMyInvitesRow, error) {
	rows, err := q.db.Query(ctx, listMyInvites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyInvitesRow
	for rows.Next() {
		var i ListMyInvitesRow
		if err := rows.Scan(
			&i.InvitedAt,
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Description,
			&i.SimplifyDebts,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedByID,
			&i.PhotoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reinviteGroupMember = `-- name: ReinviteGroupMember :one
UPDATE group_members
SET status = 'INVITED', role = 'MEMBER', joined_at = now()
WHERE id = $1
RETURNING id, group_id, user_id, role, status, joined_at
`

// joined_at doubles as invitedAt for ListMyInvites -- reset it so a
// re-invite after leaving shows up as a fresh invite, not the stale
// timestamp/ordering from the original membership.
func (q *Queries) ReinviteGroupMember(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, reinviteGroupMember, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const resendGroupInvite = `-- name: ResendGroupInvite :one
UPDATE group_members
SET joined_at = now()
WHERE id = $1 AND status = 'INVITED' AND joined_at <= now() - interval '24 hours'
RETURNING id, group_id, user_id, role, status, joined_at
`

// Roadmap P6: an admin resends a pending invite, at most once every 24
// hours (joined_at is the invite time while INVITED). No row back means
// it isn't a pending invite, or was sent too recently. Bumping joined_at
// also moves it to the top of the invitee's invites list.
func (q *Queries) ResendGroupInvite(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, resendGroupInvite, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const softDeleteGroup = `-- name: SoftDeleteGroup :exec
UPDATE groups SET deleted_at = now(), deleted_by_id = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	DeletedByID pgtype.UUID `json:"deleted_by_id"`
}

func (q *Queries) SoftDeleteGroup(ctx context.Context, arg SoftDeleteGroupParams) error {
	_, err := q.db.Exec(ctx, softDeleteGroup, arg.ID, arg.DeletedByID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = COALESCE($1, name),
    type = COALESCE($2, type),
    currency = COALESCE($3, currency),
    description = COALESCE($4, description),
    simplify_debts = COALESCE($5, simplify_debts),
    updated_at = now()
WHERE id = $6
RETURNING id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at, deleted_at, deleted_by_id, photo_path
`

type UpdateGroupParams struct {
	Name          pgtype.Text   `json:"name"`
	Type          NullGroupType `json:"type"`
	Currency      pgtype.Text   `json:"currency"`
	Description   pgtype.Text   `json:"description"`
	SimplifyDebts pgtype.Bool   `json:"simplify_debts"`
	ID            pgtype.UUID   `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Description,
		arg.SimplifyDebts,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.PhotoPath,
	)
	return i, err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :one
UPDATE group_members SET role = $2 WHERE id = $1 RETURNING id, group_id, user_id, role, status, joined_at
`

type UpdateGroupMemberRoleParams struct {
	ID   pgtype.UUID     `json:"id"`
	Role GroupMemberRole `json:"role"`
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberRole, arg.ID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const updateGroupMemberStatus = `-- name: UpdateGroupMemberStatus :one
UPDATE group_members SET status = $2 WHERE id = $1 RETURNING id, group_id, user_id, role, status, joined_at
`

type UpdateGroupMemberStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status GroupMemberStatus `json:"status"`
}

func (q *Queries) UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberStatus, arg.ID, arg.Status)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}
