// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (user_id, key, endpoint)
VALUES ($1, $2, $3)
RETURNING id, user_id, key, endpoint, response, created_at
`

type CreateIdempotencyKeyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Key      string      `json:"key"`
	Endpoint string      `json:"endpoint"`
}

// Reservation, written before the guarded operation runs -- a concurrent
// duplicate request fails fast on the unique constraint instead of racing
// to run the operation twice.
func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey, arg.UserID, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Endpoint,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE id = $1
`

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, id)
	return err
}

const getIdempotencyKeyByUserKeyEndpoint = `-- name: GetIdempotencyKeyByUserKeyEndpoint :one
SELECT id, user_id, key, endpoint, response, created_at FROM idempotency_keys WHERE user_id = $1 AND key = $2 AND endpoint = $3
`

type GetIdempotencyKeyByUserKeyEndpointParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Key      string      `json:"key"`
	Endpoint string      `json:"endpoint"`
}

func (q *Queries) GetIdempotencyKeyByUserKeyEndpoint(ctx context.Context, arg GetIdempotencyKeyByUserKeyEndpointParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKeyByUserKeyEndpoint, arg.UserID, arg.Key, arg.Endpoint)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Key,
		&i.Endpoint,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const setIdempotencyKeyResponse = `-- name: SetIdempotencyKeyResponse :exec
UPDATE idempotency_keys SET response = $2 WHERE id = $1
`

type SetIdempotencyKeyResponseParams struct {
	ID       pgtype.UUID `json:"id"`
	Response []byte      `json:"response"`
}

func (q *Queries) SetIdempotencyKeyResponse(ctx context.Context, arg SetIdempotencyKeyResponseParams) error {
	_, err := q.db.Exec(ctx, setIdempotencyKeyResponse, arg.ID, arg.Response)
	return err
}
