// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, title, body, read_at, created_at
`

type CreateNotificationParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationsBulk = `-- name: CreateNotificationsBulk :many
INSERT INTO notifications (user_id, type, title, body)
SELECT unnest($1::uuid[]), $2, $3, $4
RETURNING id, user_id, type, title, body, read_at, created_at
`

type CreateNotificationsBulkParams struct {
	UserIds []pgtype.UUID `json:"user_ids"`
	Type    string        `json:"type"`
	Title   string        `json:"title"`
	Body    string        `json:"body"`
}

// Fans the same event out to several recipients in one statement.
func (q *Queries) CreateNotificationsBulk(ctx context.Context, arg CreateNotificationsBulkParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, createNotificationsBulk,
		arg.UserIds,
		arg.Type,
		arg.Title,
		arg.Body,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, title, body, read_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, read_at, created_at FROM notifications
WHERE user_id = $1 AND (NOT $4::bool OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	UnreadOnly bool        `json:"unread_only"`
}

// (NOT unread_only OR read_at IS NULL) makes unread_only a real filter when
// true, and a no-op (all rows) when false, in one query.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.UnreadOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read_at = COALESCE(read_at, now()) WHERE id = $1 RETURNING id, user_id, type, title, body, read_at, created_at
`

// Preserves the original read_at if already read, rather than bumping it to
// now() on every call -- matches the "no-op if already read" behavior.
func (q *Queries) MarkNotificationRead(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
