// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addNotificationOptOut = `-- name: AddNotificationOptOut :exec
INSERT INTO notification_opt_outs (user_id, type) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddNotificationOptOutParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) AddNotificationOptOut(ctx context.Context, arg AddNotificationOptOutParams) error {
	_, err := q.db.Exec(ctx, addNotificationOptOut, arg.UserID, arg.Type)
	return err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, read_at, created_at, link
`

type CreateNotificationParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
	Link   pgtype.Text `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Link,
	)
	return i, err
}

const createNotificationsBulk = `-- name: CreateNotificationsBulk :many
INSERT INTO notifications (user_id, type, title, body, link)
SELECT r.user_id, $1, $2, $3, $4
FROM unnest($5::uuid[]) AS r(user_id)
WHERE NOT EXISTS (
    SELECT 1 FROM notification_opt_outs o
    WHERE o.user_id = r.user_id AND o.type = $1
)
RETURNING id, user_id, type, title, body, read_at, created_at, link
`

type CreateNotificationsBulkParams struct {
	Type    string        `json:"type"`
	Title   string        `json:"title"`
	Body    string        `json:"body"`
	Link    pgtype.Text   `json:"link"`
	UserIds []pgtype.UUID `json:"user_ids"`
}

// Fans the same event out to several recipients in one statement,
// skipping anyone who opted out of this type (notification_opt_outs).
func (q *Queries) CreateNotificationsBulk(ctx context.Context, arg CreateNotificationsBulkParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, createNotificationsBulk,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.UserIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, title, body, read_at, created_at, link FROM notifications WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Link,
	)
	return i, err
}

const isNotificationOptedOut = `-- name: IsNotificationOptedOut :one
SELECT EXISTS (
    SELECT 1 FROM notification_opt_outs WHERE user_id = $1 AND type = $2
)
`

type IsNotificationOptedOutParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) IsNotificationOptedOut(ctx context.Context, arg IsNotificationOptedOutParams) (bool, error) {
	row := q.db.QueryRow(ctx, isNotificationOptedOut, arg.UserID, arg.Type)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listNotificationOptOuts = `-- name: ListNotificationOptOuts :many
SELECT type FROM notification_opt_outs WHERE user_id = $1
`

func (q *Queries) ListNotificationOptOuts(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listNotificationOptOuts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var type_ string
		if err := rows.Scan(&type_); err != nil {
			return nil, err
		}
		items = append(items, type_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, body, read_at, created_at, link FROM notifications
WHERE user_id = $1 AND (NOT $4::bool OR read_at IS NULL)
ORDER BY created_at DESC, id DESC -- id: total order for stable paging
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	UnreadOnly bool        `json:"unread_only"`
}

// (NOT unread_only OR read_at IS NULL) makes unread_only a real filter when
// true, and a no-op (all rows) when false, in one query.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.UnreadOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Link,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications SET read_at = COALESCE(read_at, now()) WHERE id = $1 RETURNING id, user_id, type, title, body, read_at, created_at, link
`

// Preserves the original read_at if already read, rather than bumping it to
// now() on every call -- matches the "no-op if already read" behavior.
func (q *Queries) MarkNotificationRead(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Link,
	)
	return i, err
}

const removeNotificationOptOut = `-- name: RemoveNotificationOptOut :exec
DELETE FROM notification_opt_outs WHERE user_id = $1 AND type = $2
`

type RemoveNotificationOptOutParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) RemoveNotificationOptOut(ctx context.Context, arg RemoveNotificationOptOutParams) error {
	_, err := q.db.Exec(ctx, removeNotificationOptOut, arg.UserID, arg.Type)
	return err
}
