// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const setGroupPhoto = `-- name: SetGroupPhoto :one
UPDATE groups
SET photo_path = $1, updated_at = now()
WHERE id = $2
RETURNING id, name, type, currency, description, simplify_debts, created_by_id, created_at, updated_at, deleted_at, deleted_by_id, photo_path, auto_remind
`

type SetGroupPhotoParams struct {
	PhotoPath pgtype.Text `json:"photo_path"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetGroupPhoto(ctx context.Context, arg SetGroupPhotoParams) (Group, error) {
	row := q.db.QueryRow(ctx, setGroupPhoto, arg.PhotoPath, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Description,
		&i.SimplifyDebts,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedByID,
		&i.PhotoPath,
		&i.AutoRemind,
	)
	return i, err
}

const setProfileAvatar = `-- name: SetProfileAvatar :one
UPDATE profiles
SET avatar_url = $1, avatar_path = $2, updated_at = now()
WHERE id = $3
RETURNING id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username, avatar_path, auto_remind_friends
`

type SetProfileAvatarParams struct {
	AvatarUrl  pgtype.Text `json:"avatar_url"`
	AvatarPath pgtype.Text `json:"avatar_path"`
	ID         pgtype.UUID `json:"id"`
}

// avatar_url is what clients show; avatar_path is the stored object.
// Both NULL removes the photo.
func (q *Queries) SetProfileAvatar(ctx context.Context, arg SetProfileAvatarParams) (Profile, error) {
	row := q.db.QueryRow(ctx, setProfileAvatar, arg.AvatarUrl, arg.AvatarPath, arg.ID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AvatarPath,
		&i.AutoRemindFriends,
	)
	return i, err
}
