// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username FROM profiles WHERE email = $1
`

func (q *Queries) GetProfileByEmail(ctx context.Context, email pgtype.Text) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByEmail, email)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username FROM profiles WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username FROM profiles WHERE username = $1
`

// Phase 8 (AUTH-05) -- backs the username-availability check.
func (q *Queries) GetProfileByUsername(ctx context.Context, username pgtype.Text) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET display_name = COALESCE($1, display_name),
    avatar_url = COALESCE($2, avatar_url),
    username = COALESCE($3, username),
    preferred_currency = COALESCE($4, preferred_currency),
    locale = COALESCE($5, locale),
    updated_at = now()
WHERE id = $6
RETURNING id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username
`

type UpdateProfileParams struct {
	DisplayName       pgtype.Text `json:"display_name"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	Username          pgtype.Text `json:"username"`
	PreferredCurrency pgtype.Text `json:"preferred_currency"`
	Locale            pgtype.Text `json:"locale"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Username,
		arg.PreferredCurrency,
		arg.Locale,
		arg.ID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const upsertProfileByEmail = `-- name: UpsertProfileByEmail :one
INSERT INTO profiles (email, display_name)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET id = profiles.id
RETURNING id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username
`

type UpsertProfileByEmailParams struct {
	Email       pgtype.Text `json:"email"`
	DisplayName string      `json:"display_name"`
}

// Mirrors Prisma's `upsert({ where: { email }, update: {}, create: {...} })`
// -- a genuine no-op on conflict (the "id = profiles.id" self-assignment),
// so an existing profile's fields are never touched by a repeat OTP sign-in.
func (q *Queries) UpsertProfileByEmail(ctx context.Context, arg UpsertProfileByEmailParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfileByEmail, arg.Email, arg.DisplayName)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}

const upsertProfileByEmailWithNameAvatar = `-- name: UpsertProfileByEmailWithNameAvatar :one
INSERT INTO profiles (email, display_name, avatar_url)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE SET id = profiles.id
RETURNING id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at, username
`

type UpsertProfileByEmailWithNameAvatarParams struct {
	Email       pgtype.Text `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

// Same no-op-on-conflict semantics as UpsertProfileByEmail, but also seeds
// avatar_url on first insert (Google sign-in path).
func (q *Queries) UpsertProfileByEmailWithNameAvatar(ctx context.Context, arg UpsertProfileByEmailWithNameAvatarParams) (Profile, error) {
	row := q.db.QueryRow(ctx, upsertProfileByEmailWithNameAvatar, arg.Email, arg.DisplayName, arg.AvatarUrl)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
	)
	return i, err
}
