// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

// The push service said this endpoint is gone, whoever it belonged to.
func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const listPushSubscriptionsForUsers = `-- name: ListPushSubscriptionsForUsers :many
SELECT id, user_id, endpoint, keys, created_at, updated_at FROM push_subscriptions WHERE user_id = ANY($1::uuid[])
`

func (q *Queries) ListPushSubscriptionsForUsers(ctx context.Context, userIds []pgtype.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.Keys,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one

INSERT INTO push_subscriptions (user_id, endpoint, keys)
VALUES ($1, $2, $3)
ON CONFLICT (endpoint) DO UPDATE
SET user_id = EXCLUDED.user_id, keys = EXCLUDED.keys, updated_at = now()
RETURNING id, user_id, endpoint, keys, created_at, updated_at
`

type UpsertPushSubscriptionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Endpoint string      `json:"endpoint"`
	Keys     []byte      `json:"keys"`
}

// Phone/browser push (ADR-021). push_subscriptions has existed since
// 0007 (ported from the Prisma schema) but nothing used it until now.
// keys is the browser's {"p256dh": ..., "auth": ...} as-is.
// An endpoint belongs to one browser profile: the same endpoint
// re-subscribing (keys rotated, or another account signed in on that
// device) replaces the row rather than adding a second one.
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription, arg.UserID, arg.Endpoint, arg.Keys)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.Keys,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
