// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (template_expense_id, frequency, next_run_at, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, template_expense_id, frequency, next_run_at, enabled, created_at, updated_at
`

type CreateRecurringExpenseParams struct {
	TemplateExpenseID pgtype.UUID        `json:"template_expense_id"`
	Frequency         RecurringFrequency `json:"frequency"`
	NextRunAt         pgtype.Timestamptz `json:"next_run_at"`
	Enabled           bool               `json:"enabled"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.TemplateExpenseID,
		arg.Frequency,
		arg.NextRunAt,
		arg.Enabled,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.TemplateExpenseID,
		&i.Frequency,
		&i.NextRunAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecurringExpenseByID = `-- name: GetRecurringExpenseByID :one
SELECT id, template_expense_id, frequency, next_run_at, enabled, created_at, updated_at FROM recurring_expenses WHERE id = $1
`

func (q *Queries) GetRecurringExpenseByID(ctx context.Context, id pgtype.UUID) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseByID, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.TemplateExpenseID,
		&i.Frequency,
		&i.NextRunAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRecurringExpenses = `-- name: ListDueRecurringExpenses :many
SELECT id, template_expense_id, frequency, next_run_at, enabled, created_at, updated_at FROM recurring_expenses WHERE enabled = true AND next_run_at <= $1
`

func (q *Queries) ListDueRecurringExpenses(ctx context.Context, nextRunAt pgtype.Timestamptz) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listDueRecurringExpenses, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringExpense
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.TemplateExpenseID,
			&i.Frequency,
			&i.NextRunAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyRecurringExpenses = `-- name: ListMyRecurringExpenses :many
SELECT re.id, re.template_expense_id, re.frequency, re.next_run_at, re.enabled, re.created_at, re.updated_at FROM recurring_expenses re
JOIN expenses e ON e.id = re.template_expense_id
WHERE e.deleted_at IS NULL AND (
    (e.group_id IS NULL AND EXISTS (SELECT 1 FROM expense_participants ep WHERE ep.expense_id = e.id AND ep.user_id = $1))
    OR (e.group_id IS NOT NULL AND EXISTS (SELECT 1 FROM group_members gm WHERE gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'ACTIVE'))
)
ORDER BY re.next_run_at ASC
`

// Every recurring template the user is involved in, same visibility rule
// as expenses.Service.List's default view.
func (q *Queries) ListMyRecurringExpenses(ctx context.Context, userID pgtype.UUID) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listMyRecurringExpenses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringExpense
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.TemplateExpenseID,
			&i.Frequency,
			&i.NextRunAt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringExpenseEnabled = `-- name: UpdateRecurringExpenseEnabled :one
UPDATE recurring_expenses SET enabled = $2, updated_at = now() WHERE id = $1 RETURNING id, template_expense_id, frequency, next_run_at, enabled, created_at, updated_at
`

type UpdateRecurringExpenseEnabledParams struct {
	ID      pgtype.UUID `json:"id"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpdateRecurringExpenseEnabled(ctx context.Context, arg UpdateRecurringExpenseEnabledParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpenseEnabled, arg.ID, arg.Enabled)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.TemplateExpenseID,
		&i.Frequency,
		&i.NextRunAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurringExpenseNextRunAt = `-- name: UpdateRecurringExpenseNextRunAt :exec
UPDATE recurring_expenses SET next_run_at = $2, updated_at = now() WHERE id = $1
`

type UpdateRecurringExpenseNextRunAtParams struct {
	ID        pgtype.UUID        `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateRecurringExpenseNextRunAt(ctx context.Context, arg UpdateRecurringExpenseNextRunAtParams) error {
	_, err := q.db.Exec(ctx, updateRecurringExpenseNextRunAt, arg.ID, arg.NextRunAt)
	return err
}
