// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentReminderIfDue = `-- name: CreatePaymentReminderIfDue :one
INSERT INTO payment_reminders (group_id, sender_id, recipient_id)
SELECT $1, $2, $3
WHERE NOT EXISTS (
    SELECT 1 FROM payment_reminders r
    WHERE r.group_id = $1 AND r.recipient_id = $3
      AND r.created_at > now() - interval '24 hours'
)
RETURNING id, group_id, sender_id, recipient_id, created_at
`

type CreatePaymentReminderIfDueParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	SenderID    pgtype.UUID `json:"sender_id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

// Inserts only when the recipient hasn't been reminded in this group in
// the last 24 hours; no row back means it's too soon. Two admins tapping
// at the same instant could both get through -- harmless (two
// notifications), so no lock (ADR-018).
func (q *Queries) CreatePaymentReminderIfDue(ctx context.Context, arg CreatePaymentReminderIfDueParams) (PaymentReminder, error) {
	row := q.db.QueryRow(ctx, createPaymentReminderIfDue, arg.GroupID, arg.SenderID, arg.RecipientID)
	var i PaymentReminder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.RecipientID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPaymentReminder = `-- name: GetLatestPaymentReminder :one
SELECT id, group_id, sender_id, recipient_id, created_at FROM payment_reminders
WHERE group_id = $1 AND recipient_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestPaymentReminderParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
}

func (q *Queries) GetLatestPaymentReminder(ctx context.Context, arg GetLatestPaymentReminderParams) (PaymentReminder, error) {
	row := q.db.QueryRow(ctx, getLatestPaymentReminder, arg.GroupID, arg.RecipientID)
	var i PaymentReminder
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.RecipientID,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestPaymentReminders = `-- name: ListLatestPaymentReminders :many
SELECT DISTINCT ON (recipient_id) id, group_id, sender_id, recipient_id, created_at
FROM payment_reminders
WHERE group_id = $1
ORDER BY recipient_id, created_at DESC
`

// The most recent reminder per recipient in a group.
func (q *Queries) ListLatestPaymentReminders(ctx context.Context, groupID pgtype.UUID) ([]PaymentReminder, error) {
	rows, err := q.db.Query(ctx, listLatestPaymentReminders, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentReminder
	for rows.Next() {
		var i PaymentReminder
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.RecipientID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
