// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlementRequest = `-- name: CreateSettlementRequest :one
INSERT INTO settlement_requests (payer_id, recipient_id, group_id, amount, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, payer_id, recipient_id, group_id, amount, currency, receipt_path, status, settlement_id, created_at, resolved_at
`

type CreateSettlementRequestParams struct {
	PayerID     pgtype.UUID `json:"payer_id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
	GroupID     pgtype.UUID `json:"group_id"`
	Amount      int64       `json:"amount"`
	Currency    string      `json:"currency"`
}

func (q *Queries) CreateSettlementRequest(ctx context.Context, arg CreateSettlementRequestParams) (SettlementRequest, error) {
	row := q.db.QueryRow(ctx, createSettlementRequest,
		arg.PayerID,
		arg.RecipientID,
		arg.GroupID,
		arg.Amount,
		arg.Currency,
	)
	var i SettlementRequest
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.RecipientID,
		&i.GroupID,
		&i.Amount,
		&i.Currency,
		&i.ReceiptPath,
		&i.Status,
		&i.SettlementID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getSettlementRequest = `-- name: GetSettlementRequest :one
SELECT id, payer_id, recipient_id, group_id, amount, currency, receipt_path, status, settlement_id, created_at, resolved_at FROM settlement_requests WHERE id = $1
`

func (q *Queries) GetSettlementRequest(ctx context.Context, id pgtype.UUID) (SettlementRequest, error) {
	row := q.db.QueryRow(ctx, getSettlementRequest, id)
	var i SettlementRequest
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.RecipientID,
		&i.GroupID,
		&i.Amount,
		&i.Currency,
		&i.ReceiptPath,
		&i.Status,
		&i.SettlementID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const linkSettlementRequest = `-- name: LinkSettlementRequest :one
UPDATE settlement_requests SET settlement_id = $2 WHERE id = $1 RETURNING id, payer_id, recipient_id, group_id, amount, currency, receipt_path, status, settlement_id, created_at, resolved_at
`

type LinkSettlementRequestParams struct {
	ID           pgtype.UUID `json:"id"`
	SettlementID pgtype.UUID `json:"settlement_id"`
}

func (q *Queries) LinkSettlementRequest(ctx context.Context, arg LinkSettlementRequestParams) (SettlementRequest, error) {
	row := q.db.QueryRow(ctx, linkSettlementRequest, arg.ID, arg.SettlementID)
	var i SettlementRequest
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.RecipientID,
		&i.GroupID,
		&i.Amount,
		&i.Currency,
		&i.ReceiptPath,
		&i.Status,
		&i.SettlementID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listSettlementRequestsForUser = `-- name: ListSettlementRequestsForUser :many
SELECT id, payer_id, recipient_id, group_id, amount, currency, receipt_path, status, settlement_id, created_at, resolved_at FROM settlement_requests
WHERE (payer_id = $1 OR recipient_id = $1)
  AND (status = 'PENDING' OR resolved_at > now() - interval '30 days')
ORDER BY (status = 'PENDING') DESC, created_at DESC
LIMIT 100
`

// Pending requests where the user is the payer or the recipient, plus
// those resolved in the last 30 days, newest first.
func (q *Queries) ListSettlementRequestsForUser(ctx context.Context, payerID pgtype.UUID) ([]SettlementRequest, error) {
	rows, err := q.db.Query(ctx, listSettlementRequestsForUser, payerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementRequest
	for rows.Next() {
		var i SettlementRequest
		if err := rows.Scan(
			&i.ID,
			&i.PayerID,
			&i.RecipientID,
			&i.GroupID,
			&i.Amount,
			&i.Currency,
			&i.ReceiptPath,
			&i.Status,
			&i.SettlementID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenSettlementRequest = `-- name: ReopenSettlementRequest :exec
UPDATE settlement_requests SET status = 'PENDING', resolved_at = NULL
WHERE id = $1 AND settlement_id IS NULL
`

// Undoes a confirm claim when writing the settlement failed.
func (q *Queries) ReopenSettlementRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, reopenSettlementRequest, id)
	return err
}

const resolveSettlementRequest = `-- name: ResolveSettlementRequest :one
UPDATE settlement_requests
SET status = $2, resolved_at = now()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, payer_id, recipient_id, group_id, amount, currency, receipt_path, status, settlement_id, created_at, resolved_at
`

type ResolveSettlementRequestParams struct {
	ID     pgtype.UUID             `json:"id"`
	Status SettlementRequestStatus `json:"status"`
}

// Only a PENDING request can be resolved, in one atomic step: no row back
// means someone got there first (it was already confirmed, rejected or
// cancelled). Confirming claims the request this way before the
// SETTLEMENT expense is written, so it can never be confirmed twice.
func (q *Queries) ResolveSettlementRequest(ctx context.Context, arg ResolveSettlementRequestParams) (SettlementRequest, error) {
	row := q.db.QueryRow(ctx, resolveSettlementRequest, arg.ID, arg.Status)
	var i SettlementRequest
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.RecipientID,
		&i.GroupID,
		&i.Amount,
		&i.Currency,
		&i.ReceiptPath,
		&i.Status,
		&i.SettlementID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const sumPendingSettlementRequests = `-- name: SumPendingSettlementRequests :one
SELECT COALESCE(sum(amount), 0)::bigint FROM settlement_requests
WHERE payer_id = $1 AND recipient_id = $2 AND status = 'PENDING'
  AND group_id IS NOT DISTINCT FROM $3
`

type SumPendingSettlementRequestsParams struct {
	PayerID     pgtype.UUID `json:"payer_id"`
	RecipientID pgtype.UUID `json:"recipient_id"`
	GroupID     pgtype.UUID `json:"group_id"`
}

// What the payer has already claimed to have paid this recipient in the
// same scope (personal = group_id NULL) and is still waiting on, so a
// new claim can't add up past what they owe.
func (q *Queries) SumPendingSettlementRequests(ctx context.Context, arg SumPendingSettlementRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumPendingSettlementRequests, arg.PayerID, arg.RecipientID, arg.GroupID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSettlementRequestReceiptPath = `-- name: UpdateSettlementRequestReceiptPath :one
UPDATE settlement_requests SET receipt_path = $2 WHERE id = $1 RETURNING id, payer_id, recipient_id, group_id, amount, currency, receipt_path, status, settlement_id, created_at, resolved_at
`

type UpdateSettlementRequestReceiptPathParams struct {
	ID          pgtype.UUID `json:"id"`
	ReceiptPath pgtype.Text `json:"receipt_path"`
}

func (q *Queries) UpdateSettlementRequestReceiptPath(ctx context.Context, arg UpdateSettlementRequestReceiptPathParams) (SettlementRequest, error) {
	row := q.db.QueryRow(ctx, updateSettlementRequestReceiptPath, arg.ID, arg.ReceiptPath)
	var i SettlementRequest
	err := row.Scan(
		&i.ID,
		&i.PayerID,
		&i.RecipientID,
		&i.GroupID,
		&i.Amount,
		&i.Currency,
		&i.ReceiptPath,
		&i.Status,
		&i.SettlementID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
