// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendship = `-- name: AcceptFriendship :one
UPDATE friendships SET status = 'ACCEPTED' WHERE id = $1 RETURNING id, user_id, friend_id, status, created_at
`

func (q *Queries) AcceptFriendship(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, acceptFriendship, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendships (user_id, friend_id) VALUES ($1, $2) RETURNING id, user_id, friend_id, status, created_at
`

type CreateFriendshipParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FriendID pgtype.UUID `json:"friend_id"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships WHERE id = $1
`

func (q *Queries) DeleteFriendship(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFriendship, id)
	return err
}

const findFriendshipBetween = `-- name: FindFriendshipBetween :one
SELECT id, user_id, friend_id, status, created_at FROM friendships
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
LIMIT 1
`

type FindFriendshipBetweenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FriendID pgtype.UUID `json:"friend_id"`
}

func (q *Queries) FindFriendshipBetween(ctx context.Context, arg FindFriendshipBetweenParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, findFriendshipBetween, arg.UserID, arg.FriendID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, user_id, friend_id, status, created_at FROM friendships WHERE id = $1
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listFriendships = `-- name: ListFriendships :many
SELECT
    f.id AS friendship_id,
    f.created_at AS since,
    f.user_id,
    f.friend_id,
    u.display_name AS user_display_name,
    u.avatar_url AS user_avatar_url,
    u.email AS user_email,
    u.preferred_currency AS user_preferred_currency,
    u.locale AS user_locale,
    fr.display_name AS friend_display_name,
    fr.avatar_url AS friend_avatar_url,
    fr.email AS friend_email,
    fr.preferred_currency AS friend_preferred_currency,
    fr.locale AS friend_locale
FROM friendships f
JOIN profiles u ON u.id = f.user_id
JOIN profiles fr ON fr.id = f.friend_id
WHERE f.status = 'ACCEPTED' AND (f.user_id = $1 OR f.friend_id = $1)
ORDER BY f.created_at DESC
`

type ListFriendshipsRow struct {
	FriendshipID            pgtype.UUID        `json:"friendship_id"`
	Since                   pgtype.Timestamptz `json:"since"`
	UserID                  pgtype.UUID        `json:"user_id"`
	FriendID                pgtype.UUID        `json:"friend_id"`
	UserDisplayName         string             `json:"user_display_name"`
	UserAvatarUrl           pgtype.Text        `json:"user_avatar_url"`
	UserEmail               pgtype.Text        `json:"user_email"`
	UserPreferredCurrency   string             `json:"user_preferred_currency"`
	UserLocale              string             `json:"user_locale"`
	FriendDisplayName       string             `json:"friend_display_name"`
	FriendAvatarUrl         pgtype.Text        `json:"friend_avatar_url"`
	FriendEmail             pgtype.Text        `json:"friend_email"`
	FriendPreferredCurrency string             `json:"friend_preferred_currency"`
	FriendLocale            string             `json:"friend_locale"`
}

func (q *Queries) ListFriendships(ctx context.Context, userID pgtype.UUID) ([]ListFriendshipsRow, error) {
	rows, err := q.db.Query(ctx, listFriendships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendshipsRow
	for rows.Next() {
		var i ListFriendshipsRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.Since,
			&i.UserID,
			&i.FriendID,
			&i.UserDisplayName,
			&i.UserAvatarUrl,
			&i.UserEmail,
			&i.UserPreferredCurrency,
			&i.UserLocale,
			&i.FriendDisplayName,
			&i.FriendAvatarUrl,
			&i.FriendEmail,
			&i.FriendPreferredCurrency,
			&i.FriendLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT
    f.id AS friendship_id,
    f.created_at AS sent_at,
    u.id AS from_id,
    u.display_name AS from_display_name,
    u.avatar_url AS from_avatar_url,
    u.email AS from_email,
    u.preferred_currency AS from_preferred_currency,
    u.locale AS from_locale
FROM friendships f
JOIN profiles u ON u.id = f.user_id
WHERE f.friend_id = $1 AND f.status = 'PENDING'
ORDER BY f.created_at DESC
`

type ListIncomingFriendRequestsRow struct {
	FriendshipID          pgtype.UUID        `json:"friendship_id"`
	SentAt                pgtype.Timestamptz `json:"sent_at"`
	FromID                pgtype.UUID        `json:"from_id"`
	FromDisplayName       string             `json:"from_display_name"`
	FromAvatarUrl         pgtype.Text        `json:"from_avatar_url"`
	FromEmail             pgtype.Text        `json:"from_email"`
	FromPreferredCurrency string             `json:"from_preferred_currency"`
	FromLocale            string             `json:"from_locale"`
}

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, friendID pgtype.UUID) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingFriendRequests, friendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncomingFriendRequestsRow
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.FriendshipID,
			&i.SentAt,
			&i.FromID,
			&i.FromDisplayName,
			&i.FromAvatarUrl,
			&i.FromEmail,
			&i.FromPreferredCurrency,
			&i.FromLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFriendByEmailOrPhone = `-- name: SearchFriendByEmailOrPhone :one
SELECT id, display_name, avatar_url, phone, email, preferred_currency, locale, created_at, updated_at FROM profiles
WHERE id != $1 AND (email = $2 OR phone = $2)
LIMIT 1
`

type SearchFriendByEmailOrPhoneParams struct {
	ID    pgtype.UUID `json:"id"`
	Email pgtype.Text `json:"email"`
}

// Exact match only -- never a fuzzy name search, so you can't browse the
// user directory.
func (q *Queries) SearchFriendByEmailOrPhone(ctx context.Context, arg SearchFriendByEmailOrPhoneParams) (Profile, error) {
	row := q.db.QueryRow(ctx, searchFriendByEmailOrPhone, arg.ID, arg.Email)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Phone,
		&i.Email,
		&i.PreferredCurrency,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
