// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FriendshipStatus string

const (
	FriendshipStatusPENDING  FriendshipStatus = "PENDING"
	FriendshipStatusACCEPTED FriendshipStatus = "ACCEPTED"
	FriendshipStatusBLOCKED  FriendshipStatus = "BLOCKED"
)

func (e *FriendshipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipStatus(s)
	case string:
		*e = FriendshipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipStatus: %T", src)
	}
	return nil
}

type NullFriendshipStatus struct {
	FriendshipStatus FriendshipStatus `json:"friendship_status"`
	Valid            bool             `json:"valid"` // Valid is true if FriendshipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipStatus), nil
}

type GroupMemberRole string

const (
	GroupMemberRoleADMIN  GroupMemberRole = "ADMIN"
	GroupMemberRoleMEMBER GroupMemberRole = "MEMBER"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole `json:"group_member_role"`
	Valid           bool            `json:"valid"` // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type GroupMemberStatus string

const (
	GroupMemberStatusINVITED GroupMemberStatus = "INVITED"
	GroupMemberStatusACTIVE  GroupMemberStatus = "ACTIVE"
	GroupMemberStatusLEFT    GroupMemberStatus = "LEFT"
)

func (e *GroupMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberStatus(s)
	case string:
		*e = GroupMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberStatus: %T", src)
	}
	return nil
}

type NullGroupMemberStatus struct {
	GroupMemberStatus GroupMemberStatus `json:"group_member_status"`
	Valid             bool              `json:"valid"` // Valid is true if GroupMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberStatus), nil
}

type GroupType string

const (
	GroupTypeFRIENDS   GroupType = "FRIENDS"
	GroupTypeTRIP      GroupType = "TRIP"
	GroupTypeHOUSEHOLD GroupType = "HOUSEHOLD"
	GroupTypeFAMILY    GroupType = "FAMILY"
	GroupTypeTEAM      GroupType = "TEAM"
	GroupTypeOTHER     GroupType = "OTHER"
)

func (e *GroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupType(s)
	case string:
		*e = GroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupType: %T", src)
	}
	return nil
}

type NullGroupType struct {
	GroupType GroupType `json:"group_type"`
	Valid     bool      `json:"valid"` // Valid is true if GroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.GroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupType), nil
}

type OauthProvider string

const (
	OauthProviderGOOGLE OauthProvider = "GOOGLE"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider `json:"oauth_provider"`
	Valid         bool          `json:"valid"` // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type RecurringFrequency string

const (
	RecurringFrequencyDAILY   RecurringFrequency = "DAILY"
	RecurringFrequencyWEEKLY  RecurringFrequency = "WEEKLY"
	RecurringFrequencyMONTHLY RecurringFrequency = "MONTHLY"
	RecurringFrequencyYEARLY  RecurringFrequency = "YEARLY"
)

func (e *RecurringFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurringFrequency(s)
	case string:
		*e = RecurringFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurringFrequency: %T", src)
	}
	return nil
}

type NullRecurringFrequency struct {
	RecurringFrequency RecurringFrequency `json:"recurring_frequency"`
	Valid              bool               `json:"valid"` // Valid is true if RecurringFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurringFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.RecurringFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurringFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurringFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurringFrequency), nil
}

type SplitType string

const (
	SplitTypeEQUAL      SplitType = "EQUAL"
	SplitTypeEXACT      SplitType = "EXACT"
	SplitTypePERCENTAGE SplitType = "PERCENTAGE"
	SplitTypeSHARES     SplitType = "SHARES"
	SplitTypeSETTLEMENT SplitType = "SETTLEMENT"
)

func (e *SplitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SplitType(s)
	case string:
		*e = SplitType(s)
	default:
		return fmt.Errorf("unsupported scan type for SplitType: %T", src)
	}
	return nil
}

type NullSplitType struct {
	SplitType SplitType `json:"split_type"`
	Valid     bool      `json:"valid"` // Valid is true if SplitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSplitType) Scan(value interface{}) error {
	if value == nil {
		ns.SplitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SplitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSplitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SplitType), nil
}

type CurrencyRate struct {
	ID           pgtype.UUID        `json:"id"`
	CurrencyFrom string             `json:"currency_from"`
	CurrencyTo   string             `json:"currency_to"`
	Rate         pgtype.Numeric     `json:"rate"`
	FetchedAt    pgtype.Timestamptz `json:"fetched_at"`
}

type Expense struct {
	ID           pgtype.UUID        `json:"id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Name         string             `json:"name"`
	Category     string             `json:"category"`
	Amount       int64              `json:"amount"`
	Currency     string             `json:"currency"`
	PaidByID     pgtype.UUID        `json:"paid_by_id"`
	SplitType    SplitType          `json:"split_type"`
	ExpenseDate  pgtype.Timestamptz `json:"expense_date"`
	ReceiptPath  pgtype.Text        `json:"receipt_path"`
	Notes        pgtype.Text        `json:"notes"`
	ConversionID pgtype.UUID        `json:"conversion_id"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedByID  pgtype.UUID        `json:"deleted_by_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	UpdatedByID  pgtype.UUID        `json:"updated_by_id"`
}

type ExpenseNote struct {
	ID        pgtype.UUID        `json:"id"`
	ExpenseID pgtype.UUID        `json:"expense_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExpenseParticipant struct {
	ID        pgtype.UUID `json:"id"`
	ExpenseID pgtype.UUID `json:"expense_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Amount    int64       `json:"amount"`
}

type Friendship struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FriendID  pgtype.UUID        `json:"friend_id"`
	Status    FriendshipStatus   `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Type          GroupType          `json:"type"`
	Currency      string             `json:"currency"`
	Description   pgtype.Text        `json:"description"`
	SimplifyDebts bool               `json:"simplify_debts"`
	CreatedByID   pgtype.UUID        `json:"created_by_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	ID       pgtype.UUID        `json:"id"`
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     GroupMemberRole    `json:"role"`
	Status   GroupMemberStatus  `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type IdempotencyKey struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Key       string             `json:"key"`
	Endpoint  string             `json:"endpoint"`
	Response  []byte             `json:"response"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthAccount struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Provider          OauthProvider      `json:"provider"`
	ProviderAccountID string             `json:"provider_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type OtpCode struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	CodeHash   string             `json:"code_hash"`
	Attempts   int32              `json:"attempts"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Phone             pgtype.Text        `json:"phone"`
	Email             pgtype.Text        `json:"email"`
	PreferredCurrency string             `json:"preferred_currency"`
	Locale            string             `json:"locale"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type PushSubscription struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Endpoint  string             `json:"endpoint"`
	Keys      []byte             `json:"keys"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RecurringExpense struct {
	ID                pgtype.UUID        `json:"id"`
	TemplateExpenseID pgtype.UUID        `json:"template_expense_id"`
	Frequency         RecurringFrequency `json:"frequency"`
	NextRunAt         pgtype.Timestamptz `json:"next_run_at"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}
