// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptFriendship(ctx context.Context, id pgtype.UUID) (Friendship, error)
	ConsumeOtpCode(ctx context.Context, id pgtype.UUID) error
	CountActiveAdminsExcept(ctx context.Context, arg CountActiveAdminsExceptParams) (int64, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseNote(ctx context.Context, arg CreateExpenseNoteParams) (ExpenseNote, error)
	CreateExpenseParticipant(ctx context.Context, arg CreateExpenseParticipantParams) (ExpenseParticipant, error)
	CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error)
	// Reservation, written before the guarded operation runs -- a concurrent
	// duplicate request fails fast on the unique constraint instead of racing
	// to run the operation twice.
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Fans the same event out to several recipients in one statement.
	CreateNotificationsBulk(ctx context.Context, arg CreateNotificationsBulkParams) ([]Notification, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (OtpCode, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteExpenseParticipants(ctx context.Context, expenseID pgtype.UUID) error
	DeleteFriendship(ctx context.Context, id pgtype.UUID) error
	DeleteIdempotencyKey(ctx context.Context, id pgtype.UUID) error
	FindFriendshipBetween(ctx context.Context, arg FindFriendshipBetweenParams) (Friendship, error)
	GetExpenseByID(ctx context.Context, id pgtype.UUID) (Expense, error)
	GetExpenseParticipant(ctx context.Context, arg GetExpenseParticipantParams) (ExpenseParticipant, error)
	GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetGroupOwedSums(ctx context.Context, groupID pgtype.UUID) ([]GetGroupOwedSumsRow, error)
	GetGroupPaidSums(ctx context.Context, groupID pgtype.UUID) ([]GetGroupPaidSumsRow, error)
	GetIdempotencyKeyByUserKeyEndpoint(ctx context.Context, arg GetIdempotencyKeyByUserKeyEndpointParams) (IdempotencyKey, error)
	GetLatestUnconsumedOtpCode(ctx context.Context, email string) (OtpCode, error)
	GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error)
	GetOAuthAccountByProvider(ctx context.Context, arg GetOAuthAccountByProviderParams) (OauthAccount, error)
	GetPairwiseParticipantsInGroup(ctx context.Context, arg GetPairwiseParticipantsInGroupParams) ([]GetPairwiseParticipantsInGroupRow, error)
	// Personal-scope (group_id IS NULL) half of getPairwiseBalance's OR query.
	GetPairwiseParticipantsPersonal(ctx context.Context, arg GetPairwiseParticipantsPersonalParams) ([]GetPairwiseParticipantsPersonalRow, error)
	GetProfileByEmail(ctx context.Context, email pgtype.Text) (Profile, error)
	GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error)
	// Cooldown check: most recent OTP sent for this email since `since`.
	GetRecentOtpCode(ctx context.Context, arg GetRecentOtpCodeParams) (OtpCode, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) error
	ListActiveMemberIDsExcept(ctx context.Context, arg ListActiveMemberIDsExceptParams) ([]pgtype.UUID, error)
	ListExpenseNotesWithAuthor(ctx context.Context, expenseID pgtype.UUID) ([]ListExpenseNotesWithAuthorRow, error)
	ListExpenseParticipantsForExpenseIDs(ctx context.Context, expenseIds []pgtype.UUID) ([]ListExpenseParticipantsForExpenseIDsRow, error)
	ListExpensesByGroup(ctx context.Context, arg ListExpensesByGroupParams) ([]Expense, error)
	// Personal (non-group) expenses shared between the actor and a specific
	// friend -- ABRO_PRD.md §22 "Friend Balance" history list.
	ListExpensesWithFriend(ctx context.Context, arg ListExpensesWithFriendParams) ([]Expense, error)
	ListFriendships(ctx context.Context, userID pgtype.UUID) ([]ListFriendshipsRow, error)
	ListGroupMembersWithProfiles(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersWithProfilesRow, error)
	ListIncomingFriendRequests(ctx context.Context, friendID pgtype.UUID) ([]ListIncomingFriendRequestsRow, error)
	ListMyActiveGroups(ctx context.Context, userID pgtype.UUID) ([]Group, error)
	// Personal (non-group) expenses the actor participates in, plus every
	// expense in a group the actor is an ACTIVE member of.
	ListMyExpenses(ctx context.Context, arg ListMyExpensesParams) ([]Expense, error)
	ListMyInvites(ctx context.Context, userID pgtype.UUID) ([]ListMyInvitesRow, error)
	// (NOT unread_only OR read_at IS NULL) makes unread_only a real filter when
	// true, and a no-op (all rows) when false, in one query.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error
	// Preserves the original read_at if already read, rather than bumping it to
	// now() on every call -- matches the "no-op if already read" behavior.
	MarkNotificationRead(ctx context.Context, id pgtype.UUID) (Notification, error)
	// joined_at doubles as invitedAt for ListMyInvites -- reset it so a
	// re-invite after leaving shows up as a fresh invite, not the stale
	// timestamp/ordering from the original membership.
	ReinviteGroupMember(ctx context.Context, id pgtype.UUID) (GroupMember, error)
	RevokeSessionsByTokenHash(ctx context.Context, tokenHash string) error
	// Exact match only -- never a fuzzy name search, so you can't browse the
	// user directory.
	SearchFriendByEmailOrPhone(ctx context.Context, arg SearchFriendByEmailOrPhoneParams) (Profile, error)
	SetIdempotencyKeyResponse(ctx context.Context, arg SetIdempotencyKeyResponseParams) error
	SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error
	TouchSessionLastUsed(ctx context.Context, id pgtype.UUID) error
	// Editing an expense resubmits the whole thing -- a full overwrite, not a
	// partial COALESCE update (see updateExpenseSchema == createExpenseSchema).
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateExpenseReceiptPath(ctx context.Context, arg UpdateExpenseReceiptPathParams) (Expense, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error)
	UpdateGroupMemberStatus(ctx context.Context, arg UpdateGroupMemberStatusParams) (GroupMember, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	// Mirrors Prisma's `upsert({ where: { email }, update: {}, create: {...} })`
	// -- a genuine no-op on conflict (the "id = profiles.id" self-assignment),
	// so an existing profile's fields are never touched by a repeat OTP sign-in.
	UpsertProfileByEmail(ctx context.Context, arg UpsertProfileByEmailParams) (Profile, error)
	// Same no-op-on-conflict semantics as UpsertProfileByEmail, but also seeds
	// avatar_url on first insert (Google sign-in path).
	UpsertProfileByEmailWithNameAvatar(ctx context.Context, arg UpsertProfileByEmailWithNameAvatarParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
