// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeOtpCode(ctx context.Context, id pgtype.UUID) error
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreateOtpCode(ctx context.Context, arg CreateOtpCodeParams) (OtpCode, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	GetLatestUnconsumedOtpCode(ctx context.Context, email string) (OtpCode, error)
	GetOAuthAccountByProvider(ctx context.Context, arg GetOAuthAccountByProviderParams) (OauthAccount, error)
	GetProfileByEmail(ctx context.Context, email pgtype.Text) (Profile, error)
	GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error)
	// Cooldown check: most recent OTP sent for this email since `since`.
	GetRecentOtpCode(ctx context.Context, arg GetRecentOtpCodeParams) (OtpCode, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	IncrementOtpAttempts(ctx context.Context, id pgtype.UUID) error
	RevokeSessionsByTokenHash(ctx context.Context, tokenHash string) error
	TouchSessionLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	// Mirrors Prisma's `upsert({ where: { email }, update: {}, create: {...} })`
	// -- a genuine no-op on conflict (the "id = profiles.id" self-assignment),
	// so an existing profile's fields are never touched by a repeat OTP sign-in.
	UpsertProfileByEmail(ctx context.Context, arg UpsertProfileByEmailParams) (Profile, error)
	// Same no-op-on-conflict semantics as UpsertProfileByEmail, but also seeds
	// avatar_url on first insert (Google sign-in path).
	UpsertProfileByEmailWithNameAvatar(ctx context.Context, arg UpsertProfileByEmailWithNameAvatarParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
